version: 2.0

jobs:
  lint:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i
      - run:
          name: Lint
          command: |
            npm run lint

workflows:
    version: 2
    build:
      jobs:
        - lint